sudo: required
language: node_js
services:
  - docker
node_js:
  - "4.2.6"
branches:
  only:
    - /^v\d+.\d+.\d+/
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm -g install npm@latest
  - npm install -g bower gulp
  - npm install
  - npm install phantomjs
  - npm install -g karma
  - bower install
script:
  - gulp build
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t $DOCKER_IMAGE_NAME .
  - if [ ! -z "$TRAVIS_TAG" ]; then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG; fi && docker push $DOCKER_IMAGE_NAME

notifications:
  slack: krysztalowepulpety:hHLE5HwACe8xjFsSD2ramKt1