sudo: required
language: node_js
services:
  - docker
node_js:
  - "4.2.6"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - bower_components
install:
  - npm -g install npm@latest
  - npm install -g bower gulp
  - npm install
  - npm install phantomjs
  - npm install -g karma
  - bower install
script:
  - gulp build
after_success:
  - sudo ./deploy_docker_image.sh $VPS_IP
notifications:
  slack: krysztalowepulpety:hHLE5HwACe8xjFsSD2ramKt1